const mongoose = require("mongoose");
const tyre = require("./models/Tyres");
const dotenv = require('dotenv');

dotenv.config();

// Connect to MongoDB
mongoose.connect(process.env.MONGO_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true
});

const tyres = [
  {
    brand: "MRF",
    model: "Zapper Q",
    images: ["tyre1.jpg"],
    price: "₹3,200",
    originalPrice: "₹3,800",
    discount: "15%",
    size: "90/90-17",
    type: "Tubeless",
    pattern: "Sport",
    compound: "Soft",
    maxLoad: "150kg",
    maxSpeed: "180km/h",
    offers: ["Free fitting"],
    features: ["Excellent grip", "Long life"],
    priority: 1
  },
  {
    brand: "CEAT",
    model: "Zoom XL",
    images: ["tyre2.webp"],
    price: "₹2,900",
    originalPrice: "₹3,500",
    discount: "17%",
    size: "100/80-17",
    type: "Tubeless",
    pattern: "Street",
    compound: "Medium",
    maxLoad: "140kg",
    maxSpeed: "160km/h",
    offers: ["Free nitrogen fill"],
    features: ["High stability", "Good wet traction"],
    priority: 2
  },
  {
    brand: "Apollo",
    model: "ActiGrip R5",
    images: ["tyre3.jpg"],
    price: "₹3,000",
    originalPrice: "₹3,700",
    discount: "19%",
    size: "110/90-18",
    type: "Tube Type",
    pattern: "All-terrain",
    compound: "Hard",
    maxLoad: "160kg",
    maxSpeed: "170km/h",
    offers: ["2-year warranty"],
    features: ["Durable", "Off-road capable"],
    priority: 3
  },
  {
    brand: "Michelin",
    model: "Pilot Street",
    images: ["tyre1.jpg"],
    price: "₹4,200",
    originalPrice: "₹5,000",
    discount: "16%",
    size: "140/70-17",
    type: "Tubeless",
    pattern: "Sport Touring",
    compound: "Medium",
    maxLoad: "180kg",
    maxSpeed: "200km/h",
    offers: ["Free installation"],
    features: ["Smooth ride", "Low noise"],
    priority: 4
  },
  {
    brand: "Pirelli",
    model: "Angel City",
    images: ["tyre2.webp"],
    price: "₹4,500",
    originalPrice: "₹5,200",
    discount: "13%",
    size: "120/70-17",
    type: "Tubeless",
    pattern: "Street",
    compound: "Soft",
    maxLoad: "170kg",
    maxSpeed: "210km/h",
    offers: ["Road hazard warranty"],
    features: ["Superior grip", "Premium feel"],
    priority: 5
  },
  {
    brand: "MRF",
    model: "Zapper Y",
    images: ["tyre3.jpg"],
    price: "₹3,100",
    originalPrice: "₹3,600",
    discount: "14%",
    size: "80/100-18",
    type: "Tube Type",
    pattern: "Standard",
    compound: "Hard",
    maxLoad: "140kg",
    maxSpeed: "150km/h",
    offers: ["Free tube"],
    features: ["Good wear resistance", "Stable handling"],
    priority: 6
  },
  {
    brand: "CEAT",
    model: "Gripp XL",
    images: ["tyre1.jpg"],
    price: "₹2,800",
    originalPrice: "₹3,200",
    discount: "12%",
    size: "90/90-19",
    type: "Tube Type",
    pattern: "Off-road",
    compound: "Medium",
    maxLoad: "150kg",
    maxSpeed: "140km/h",
    offers: ["Free fitting"],
    features: ["Strong sidewalls", "Great off-road control"],
    priority: 7
  },
  {
    brand: "Apollo",
    model: "Alpha H1",
    images: ["tyre2.webp"],
    price: "₹4,000",
    originalPrice: "₹4,600",
    discount: "13%",
    size: "110/70 ZR17",
    type: "Tubeless",
    pattern: "High Performance",
    compound: "Soft",
    maxLoad: "160kg",
    maxSpeed: "240km/h",
    offers: ["Free balancing"],
    features: ["Excellent cornering", "Race-inspired design"],
    priority: 8
  },
  {
    brand: "Michelin",
    model: "City Pro",
    images: ["tyre3.jpg"],
    price: "₹3,600",
    originalPrice: "₹4,200",
    discount: "14%",
    size: "90/90-17",
    type: "Tubeless",
    pattern: "Commuter",
    compound: "Hard",
    maxLoad: "150kg",
    maxSpeed: "180km/h",
    offers: ["Puncture resistant"],
    features: ["Longer tread life", "Reliable wet grip"],
    priority: 9
  },
  {
    brand: "Pirelli",
    model: "Diablo Rosso II",
    images: ["tyre1.jpg"],
    price: "₹6,000",
    originalPrice: "₹7,200",
    discount: "16%",
    size: "180/55 ZR17",
    type: "Tubeless",
    pattern: "Sport",
    compound: "Soft",
    maxLoad: "200kg",
    maxSpeed: "270km/h",
    offers: ["Free fitting", "Track day support"],
    features: ["Superb grip", "Quick warm-up"],
    priority: 10
  },
  {
    brand: "MRF",
    model: "Nylogrip Plus",
    images: ["tyre2.webp"],
    price: "₹2,500",
    originalPrice: "₹2,900",
    discount: "14%",
    size: "3.00-18",
    type: "Tube Type",
    pattern: "Standard",
    compound: "Hard",
    maxLoad: "130kg",
    maxSpeed: "120km/h",
    offers: ["Free tube"],
    features: ["Good durability", "Stable ride"],
    priority: 11
  },
  {
    brand: "CEAT",
    model: "Milaze",
    images: ["tyre3.jpg"],
    price: "₹2,400",
    originalPrice: "₹2,800",
    discount: "14%",
    size: "2.75-18",
    type: "Tube Type",
    pattern: "Economy",
    compound: "Hard",
    maxLoad: "125kg",
    maxSpeed: "110km/h",
    offers: ["Free fitting"],
    features: ["High mileage", "Budget friendly"],
    priority: 12
  },
  {
    brand: "Apollo",
    model: "ActiGrip F3",
    images: ["tyre1.jpg"],
    price: "₹3,100",
    originalPrice: "₹3,500",
    discount: "11%",
    size: "100/90-17",
    type: "Tubeless",
    pattern: "Dual-purpose",
    compound: "Medium",
    maxLoad: "145kg",
    maxSpeed: "160km/h",
    offers: ["2-year warranty"],
    features: ["Versatile", "Balanced performance"],
    priority: 13
  },
  {
    brand: "Michelin",
    model: "Sirac Street",
    images: ["tyre2.webp"],
    price: "₹3,500",
    originalPrice: "₹4,000",
    discount: "12%",
    size: "120/80-18",
    type: "Tube Type",
    pattern: "Touring",
    compound: "Medium",
    maxLoad: "155kg",
    maxSpeed: "170km/h",
    offers: ["Free installation"],
    features: ["Comfort ride", "Low rolling resistance"],
    priority: 14
  },
  {
    brand: "Pirelli",
    model: "Scorpion Rally STR",
    images: ["tyre3.jpg"],
    price: "₹5,800",
    originalPrice: "₹6,500",
    discount: "11%",
    size: "150/70 R17",
    type: "Tubeless",
    pattern: "Adventure",
    compound: "Medium",
    maxLoad: "190kg",
    maxSpeed: "210km/h",
    offers: ["Free balancing"],
    features: ["Excellent off-road traction", "Durable tread"],
    priority: 15
  },
  {
    brand: "MRF",
    model: "MoGrip Meteor",
    images: ["tyre1.jpg"],
    price: "₹3,200",
    originalPrice: "₹3,800",
    discount: "16%",
    size: "100/90-19",
    type: "Tube Type",
    pattern: "On/Off-road",
    compound: "Medium",
    maxLoad: "150kg",
    maxSpeed: "150km/h",
    offers: ["Free tube"],
    features: ["Strong grip", "Rugged design"],
    priority: 16
  },
  {
    brand: "CEAT",
    model: "Secura Zoom",
    images: ["tyre2.webp"],
    price: "₹2,900",
    originalPrice: "₹3,300",
    discount: "12%",
    size: "80/100-17",
    type: "Tubeless",
    pattern: "Street",
    compound: "Soft",
    maxLoad: "135kg",
    maxSpeed: "140km/h",
    offers: ["Free nitrogen fill"],
    features: ["Quick braking", "Smooth handling"],
    priority: 17
  },
  {
    brand: "Apollo",
    model: "ActiZip R4",
    images: ["tyre3.jpg"],
    price: "₹3,000",
    originalPrice: "₹3,500",
    discount: "14%",
    size: "90/100-10",
    type: "Tubeless",
    pattern: "Scooter",
    compound: "Medium",
    maxLoad: "110kg",
    maxSpeed: "120km/h",
    offers: ["1-year warranty"],
    features: ["Excellent scooter grip", "Long-lasting"],
    priority: 18
  },
  {
    brand: "Michelin",
    model: "Pilot Power 2CT",
    images: ["tyre1.jpg"],
    price: "₹7,000",
    originalPrice: "₹8,000",
    discount: "12%",
    size: "120/70 ZR17",
    type: "Tubeless",
    pattern: "Super Sport",
    compound: "Dual",
    maxLoad: "180kg",
    maxSpeed: "280km/h",
    offers: ["Track support"],
    features: ["Maximum grip", "Advanced compound tech"],
    priority: 19
  },
  {
    brand: "Pirelli",
    model: "MT 60 RS",
    images: ["tyre2.webp"],
    price: "₹6,200",
    originalPrice: "₹7,000",
    discount: "11%",
    size: "160/60 R17",
    type: "Tubeless",
    pattern: "Scrambler",
    compound: "Medium",
    maxLoad: "180kg",
    maxSpeed: "220km/h",
    offers: ["Free fitting"],
    features: ["Retro style", "Great grip"],
    priority: 20
  }
];


// Insert into MongoDB
const seedTyres = async () => {
  try {
    await tyre.deleteMany(); 
    await tyre.insertMany(tyres);
    console.log("✅ Tyre data seeded successfully.");
    mongoose.connection.close();
  } catch (err) {
    console.error("❌ Error seeding data:", err);
    mongoose.connection.close();
  }
};

seedTyres();
